name: Lint
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - run: corepack enable
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: yarn
    - run: yarn install --immutable
    - run: yarn lint
